import{a as h,S as m,i as n}from"./assets/vendor-64b55ca9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&t(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();async function y(i,r=1){const t={key:"42320428-e8ed9ab9e474091db19815d3a",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40};try{const e=new URLSearchParams(t).toString();return(await h.get(`https://pixabay.com/api/?${e}`)).data}catch{throw new Error("Failed to fetch data")}}const u={formEL:document.querySelector(".js-search-form"),listEL:document.querySelector(".gallery")};let c=null;function p(i){const r={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.9,scaleImageToRatio:!0},a=i.hits.map(t=>`<li class="gallery-item"><a href="${t.webformatURL}">
          <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}"></a>
          <div class="bloc-content">
          <p><b>Likes: </b>${t.likes}</p>
          <p><b>Views: </b>${t.views}</p>
          <p><b>Comments: </b>${t.comments}</p>
          <p><b>Downloads: </b>${t.downloads}</p>
          </div>
          </li>`).join("");u.listEL.insertAdjacentHTML("beforeend",a),c&&c.destroy(),c=new m(".gallery a",r),u.formEL.reset()}const d={lastSearchData:null},o={formEL:document.querySelector(".js-search-form"),loaderEl:document.querySelector(".loader"),galleryList:document.querySelector(".gallery"),buttonLoad:document.querySelector(".btn-load"),loaderMore:document.querySelector(".loader-more")};o.loaderEl.style.display="none";o.loaderMore.style.display="none";o.formEL.addEventListener("submit",async i=>{i.preventDefault();const r=i.target.elements.query.value.trim();if(!r){n.show({message:"Please enter a valid search query.",backgroundColor:"red",position:"topRight"});return}o.galleryList.innerHTML="",o.loaderEl.style.display="block";try{const a=await y(r);d.lastSearchData=r,a.hits.length?(p(a),a.hits.length>=40&&(o.buttonLoad.style.display="block")):(o.buttonLoad.style.display="none",n.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",position:"topRight"}))}catch{n.show({message:"An error occurred while fetching images. Please try again later.",backgroundColor:"red",position:"topRight"})}finally{o.loaderEl.style.display="none"}i.target.reset()});o.buttonLoad.addEventListener("click",async i=>{if(!d.lastSearchData)return;const r=Math.ceil(o.galleryList.children.length/40)+1;o.loaderMore.style.display="block";try{const a=await y(d.lastSearchData,r);if(p(a),a.hits.length>=40){const t=o.galleryList.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}catch{o.buttonLoad.style.display="none",n.show({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"blue",position:"topRight"})}finally{o.loaderMore.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
