import{a as p,S as m,i as l}from"./assets/vendor-64b55ca9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&t(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function t(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();async function y(i,r=1){const t={key:"42320428-e8ed9ab9e474091db19815d3a",q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40};try{const e=new URLSearchParams(t).toString();return(await p.get(`https://pixabay.com/api/?${e}`)).data}catch{throw new Error("Failed to fetch data")}}const u={formEL:document.querySelector(".js-search-form"),listEL:document.querySelector(".gallery")};let c=null;function h(i){const r={captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",animation:250,widthRatio:.9,scaleImageToRatio:!0},o=i.hits.map(t=>`<li class="gallery-item"><a href="${t.webformatURL}">
          <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}"></a>
          <div class="bloc-content">
          <p><b>Likes: </b>${t.likes}</p>
          <p><b>Views: </b>${t.views}</p>
          <p><b>Comments: </b>${t.comments}</p>
          <p><b>Downloads: </b>${t.downloads}</p>
          </div>
          </li>`).join("");u.listEL.insertAdjacentHTML("beforeend",o),c&&c.destroy(),c=new m(".gallery a",r),u.formEL.reset()}const d={lastSearchData:null},a={formEL:document.querySelector(".js-search-form"),loaderEl:document.querySelector(".loader"),galleryList:document.querySelector(".gallery"),buttonLoad:document.querySelector(".btn-load"),loaderMore:document.querySelector(".loader-more")};a.loaderEl.style.display="none";a.loaderMore.style.display="none";a.formEL.addEventListener("submit",async i=>{i.preventDefault();const r=i.target.elements.query.value.trim();if(!r){l.show({message:"Please enter a valid search query.",backgroundColor:"red",position:"topRight"});return}a.galleryList.innerHTML="",a.loaderEl.style.display="block";try{const o=await y(r);d.lastSearchData=r,o.hits.length?(h(o),o.hits.length>=40&&(a.buttonLoad.style.display="block")):l.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",position:"topRight"})}catch{l.show({message:"An error occurred while fetching images. Please try again later.",backgroundColor:"red",position:"topRight"})}finally{a.loaderEl.style.display="none"}i.target.reset()});a.buttonLoad.addEventListener("click",async i=>{if(!d.lastSearchData)return;const r=Math.ceil(a.galleryList.children.length/40)+1;a.loaderMore.style.display="block";try{const o=await y(d.lastSearchData,r);if(h(o),o.hits.length>=40){const t=a.galleryList.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}catch{a.buttonLoad.style.display="none",l.show({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"blue",position:"topRight"})}finally{a.loaderMore.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
